import { v4 as uuidv4 } from 'https://jspm.dev/uuid'

export const tweetsData = [   
    {
        handle: `@Abdel66756542 💎`,
        profilePic: `images/abdel.jpg`,
        likes: 2742,
        retweets: 104,
        tweetText: `Now this the time, I want to anounce you guys that I reached to France 😂😂😂,
             and I'm very happy that you guys are hearing from me!!!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: `${uuidv4()}`,
    },    
    {
        handle: `@Yonos ✅✅✅`,
        profilePic: `images/yonos.jpg`,
        likes: 6500,
        retweets: 234,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
                  {
                handle: `@Sakina Roy ✅`,
                profilePic: `images/sakina.jpg`,
                tweetText: `Yes! Sign me up! 😎🛩`,
                likes: 500,
            },
                  {
                handle: `@Mortaza dady ✅`,
                profilePic: `images/mortaza.jpg`,
                tweetText: `I went last year😴`,
                likes: 698,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `${uuidv4()}`,
    },
        {
        handle: `@RoyaCoder12`,
        profilePic: `images/roya.jpg`,
        likes: 10544,
        retweets: 443,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/sharif.jpg`,
                tweetText: `No. Onviosuly not. Go get a job in McDonald's.`,
                likes: 0,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/waris2.jpg`,
                tweetText: `You are wonderful just as you are! ❤️`,
                likes: 640,
            },
            {
                handle: `@Sakina Roy ✅`,
                profilePic: `images/sakina.jpg`,
                tweetText: `Yes! Sign me up! 😎🛩`,
                likes: 69,
            },
                  {
                handle: `@Mortaza dady ✅`,
                profilePic: `images/mortaza.jpg`,
                tweetText: `I went last year😴`,
                likes: 6,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `${uuidv4()}`,
    },
    {
        handle: `@reza675`,
        profilePic: `images/reza.jpg`,
        likes: 105,
        retweets: 56,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@Reza ☣️`,
                profilePic: `images/reza.JPG`,
                tweetText: `No. Onviosuly not. Go get a job in McDonald's.`,
                likes: 32,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/waris2.jpg`,
                tweetText: `You are wonderful just as you are! ❤️`,
                likes: 342,
            },
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/sharif.jpg`,
                tweetText: `No. Onviosuly not. Go get a job in McDonald's.`,
                likes: 989,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/waris2.jpg`,
                tweetText: `You are wonderful just as you are! ❤️`,
                likes: 112,
            },
            {
                handle: `@Sakina Roy ✅`,
                profilePic: `images/sakina.jpg`,
                tweetText: `Yes! Sign me up! 😎🛩`,
                likes: 612,
            },
                  {
                handle: `@Mortaza dady ✅`,
                profilePic: `images/mortaza.jpg`,
                tweetText: `I went last year😴`,
                likes: 99,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `${uuidv4()}`,
    },{
        handle: `@Zaini132`,
        profilePic: `images/zaini.JPG`,
        likes: 567,
        retweets: 34,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/sharif.jpg`,
                tweetText: `No. Onviosuly not. Go get a job in McDonald's.`,
                likes: 100,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/waris2.jpg`,
                tweetText: `You are wonderful just as you are! ❤️`,
                likes: 65,
            },
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/sharif.jpg`,
                tweetText: `No. Onviosuly not. Go get a job in McDonald's.`,
                likes: 600,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/waris2.jpg`,
                tweetText: `You are wonderful just as you are! ❤️`,
                likes: 250,
            },
            {
                handle: `@Sakina Roy ✅`,
                profilePic: `images/sakina.jpg`,
                tweetText: `Yes! Sign me up! 😎🛩`,
                likes: 111,
            },
                  {
                handle: `@Mortaza dady ✅`,
                profilePic: `images/mortaza.jpg`,
                tweetText: `I went last year😴`,
                likes: 987,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `${uuidv4()}`,
    },     
]
